"""
可调偏好多目标绿波模型的权重扫描评估脚本。
(Preference sweep evaluation script for the tunable multi-objective green-wave model.)

本脚本不训练模型，只加载已经训练好的 tunable PPO 模型，对不同 preference vector 逐个运行
确定性 SUMO 测试。它的作用是把“权重范围”变成可比较的数据表，便于后续画出等待时间、
no-stop rate、支路保护等指标随权重变化的关系。
(This script evaluates a trained tunable PPO policy under multiple preference vectors.)

模型和结果均从当前正式模块的 models/logs 目录读取与保存。
Models and results are read from and saved to this formal module's models/logs folders.
"""

import os
import random
from collections import defaultdict

import numpy as np
import pandas as pd
import traci
import torch
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import VecNormalize
from sumo_rl import parallel_env
import supersuit as ss


# Small PPO MLP inference is much faster with one CPU thread; this does not alter policy outputs.
TORCH_THREADS = int(os.environ.get("JUC_TORCH_THREADS", "1"))
torch.set_num_threads(TORCH_THREADS)
try:
    torch.set_num_interop_threads(TORCH_THREADS)
except RuntimeError:
    pass

import train as base
from train import (
    MORL_OBJECTIVE_NAMES,
    PREFERENCE_MANAGER,
    PREFERENCE_RANGES,
    normalize_morl_weights,
)

MORLBidirectionalETAObservationFunction = base.get_observation_class()
custom_bidirectional_green_wave_morl_reward = base.tunable_morl_reward


# RUN_IDX 选择待评估模型，所有输入输出路径都保留在当前正式模块中。
# RUN_IDX selects the evaluated model, and all paths remain inside this formal module.
RUN_IDX = int(os.environ.get("JUC_RUN_IDX", "1"))
MODEL_BASENAME = "ppo_marl_model_bidirectional_eta_morl_tunable"
VEC_NORM_BASENAME = "vec_normalize_marl_bidirectional_eta_morl_tunable"

NET_PATH = str(base.NET_FILE)
ROUTE_PATH = str(base.ROUTE_FILE)
RUN_DIR = str(base.MODELS_DIR / f"{base.RUN_PREFIX}{RUN_IDX}")
MODEL_PATH = os.path.join(RUN_DIR, f"{MODEL_BASENAME}.zip")
VEC_NORM_PATH = os.path.join(RUN_DIR, f"{VEC_NORM_BASENAME}.pkl")

LOG_DIR = str(base.LOGS_DIR / f"{base.RUN_PREFIX}{RUN_IDX}")
OUTPUT_DIR = os.path.join(LOG_DIR, "tunable_preference_sweep")
RESULT_CSV = os.path.join(OUTPUT_DIR, "tunable_sweep_results.csv")


# 仿真与扫描配置：第一版默认扫描 delay 和 green_wave 的二维网格，其它目标固定在区间中点。
# (Simulation and sweep settings: scan delay-green_wave by default.)
SIM_SECONDS = int(os.environ.get("JUC_SIM_SECONDS", "3600"))
MIN_GREEN = 5
MAX_GREEN = 55
SWEEP_MODE = os.environ.get("JUC_SWEEP_MODE", "grid").strip().lower()
GRID_STEPS = int(os.environ.get("JUC_SWEEP_GRID_STEPS", "5"))
OFAT_STEPS = int(os.environ.get("JUC_OFAT_STEPS", "5"))
RANDOM_SAMPLES = int(os.environ.get("JUC_SWEEP_RANDOM_SAMPLES", "40"))
MAX_ROWS = int(os.environ.get("JUC_SWEEP_MAX_ROWS", "0"))
USE_GUI = os.environ.get("JUC_USE_GUI", "0") == "1"
EVALUATION_SEEDS = tuple(
    int(value.strip())
    for value in os.environ.get("JUC_EVAL_SEEDS", "8848,8849,8850,8851,8852").split(",")
    if value.strip()
)
RESUME = os.environ.get("JUC_SWEEP_RESUME", "1") == "1"

if SWEEP_MODE == "ofat":
    RESULT_CSV = os.path.join(OUTPUT_DIR, "tunable_ofat_results_raw.csv")
RESULT_CSV = os.environ.get("JUC_SWEEP_RESULT_CSV", RESULT_CSV)


# 信号灯与路由分组：主路绿灯必须根据完整灯色 state 判断，而不是 phase 编号。
# (Signal and route groups: main green must be identified by full signal state.)
SIGNALS = ("A0", "B0", "C0")
MAIN_ROUTES = ("WE_MAIN", "EW_MAIN")
ROUTE_PREFIXES = (
    "WE_MAIN",
    "EW_MAIN",
    "NS_A0",
    "SN_A0",
    "NS_B0",
    "SN_B0",
    "NS_C0",
    "SN_C0",
)

# 主路连续性分段：用于统计 A-B、B-C、C-B、B-A 段是否无停车通过。
# (Progression segments: measure no-stop passage on arterial links.)
PROGRESSION_SEGMENTS = {
    "WE_MAIN": (("A0_B0", "A0B0"), ("B0_C0", "B0C0")),
    "EW_MAIN": (("C0_B0", "C0B0"), ("B0_A0", "B0A0")),
}
SEGMENT_BY_EDGE = {
    edge_id: (route_group, segment_name)
    for route_group, segments in PROGRESSION_SEGMENTS.items()
    for segment_name, edge_id in segments
}


def ensure_inputs_exist():
    # 评估必须同时具备路网、交通流、模型和 VecNormalize 文件。
    # (Evaluation requires network, routes, model, and VecNormalize statistics.)
    required_paths = [NET_PATH, ROUTE_PATH, MODEL_PATH, VEC_NORM_PATH]
    missing = [path for path in required_paths if not os.path.exists(path)]
    if missing:
        print("Missing required files:\n" + "\n".join(missing))
        return False
    return True


def route_group(veh_id):
    # 车辆 ID 由交通流生成脚本写入前缀，因此可以用前缀识别主路/支路来源。
    # (Vehicle IDs carry route prefixes generated by the traffic generator.)
    for prefix in ROUTE_PREFIXES:
        if veh_id.startswith(prefix):
            return prefix
    return "OTHER"


def route_type(group):
    return "main" if group in MAIN_ROUTES else "side"


def safe_traci(default, func, *args):
    # SUMO 车辆可能在同一步离开路网，安全调用可以避免偶发查询失败中断整轮扫描。
    # (Vehicles may leave within the current step; safe calls keep evaluation running.)
    try:
        return func(*args)
    except Exception:
        return default


def preference_to_arrays(weights):
    # 同时保存 raw 权重和实际输入神经网络的归一化权重，便于画图时解释坐标轴。
    # (Store normalized preferences in the fixed MORL objective order.)
    return {f"weight_{name}": float(weights[name]) for name in MORL_OBJECTIVE_NAMES}


def raw_midpoint():
    # 取中点
    return {
        name: (PREFERENCE_RANGES[name][0] + PREFERENCE_RANGES[name][1]) / 2.0
        for name in MORL_OBJECTIVE_NAMES
    }


def make_preference(label, raw_weights):
    # raw_weights 是扫描空间里的点，normalize_morl_weights 才是模型真正看到的 preference。
    # (The raw point is normalized before being passed to the trained policy.)
    normalized = normalize_morl_weights(raw_weights)
    row = {"preference_id": label}
    row.update({f"raw_{name}": float(raw_weights[name]) for name in MORL_OBJECTIVE_NAMES})
    row.update(preference_to_arrays(normalized))
    return label, raw_weights, normalized, row


def generate_representative_preferences():
    # 代表点用于快速检查：中点、各目标偏高、以及几个常见折中点。
    # (Representative points are a quick sanity check before a full grid sweep.)
    midpoint = raw_midpoint()
    specs = []
    specs.append(("midpoint", midpoint))

    for target in MORL_OBJECTIVE_NAMES:
        raw = midpoint.copy()
        raw[target] = PREFERENCE_RANGES[target][1]
        specs.append((f"{target}_high", raw))

    pair_specs = (
        ("delay_green_high", ("delay", "green_wave")),
        ("delay_side_high", ("delay", "side_fairness")),
        ("green_side_high", ("green_wave", "side_fairness")),
    )
    for label, targets in pair_specs:
        raw = midpoint.copy()
        for target in targets:
            raw[target] = PREFERENCE_RANGES[target][1]
        specs.append((label, raw))

    return [make_preference(label, raw) for label, raw in specs]


def generate_grid_preferences():
    # 二维网格优先扫描 delay 和 green_wave，因为这两个目标最直接对应“低等待”和“绿波形态”。
    # 其它三个目标固定为区间中点，避免一开始就进入五维网格导致测试量爆炸。
    # (Scan delay and green_wave first; keep other objectives at their midpoint.)
    midpoint = raw_midpoint()
    delay_values = np.linspace(*PREFERENCE_RANGES["delay"], GRID_STEPS)
    green_values = np.linspace(*PREFERENCE_RANGES["green_wave"], GRID_STEPS)

    preferences = []
    for delay_value in delay_values:
        for green_value in green_values:
            raw = midpoint.copy()
            raw["delay"] = float(delay_value)
            raw["green_wave"] = float(green_value)
            label = f"grid_d{delay_value:.3f}_g{green_value:.3f}"
            preferences.append(make_preference(label, raw))
    return preferences


def generate_ofat_preferences():
    """Sweep one raw objective weight while keeping the other four at raw midpoints."""
    midpoint = raw_midpoint()
    preferences = []
    for target in MORL_OBJECTIVE_NAMES:
        low, high = PREFERENCE_RANGES[target]
        for level_index, target_value in enumerate(np.linspace(low, high, OFAT_STEPS)):
            sweep_level = level_index / (OFAT_STEPS - 1) if OFAT_STEPS > 1 else 0.5
            raw = midpoint.copy()
            raw[target] = float(target_value)
            label = f"ofat_{target}_{level_index:02d}"
            preference = make_preference(label, raw)
            normalized = preference[2]
            preference[3].update(
                {
                    "sweep_objective": target,
                    "sweep_level": float(sweep_level),
                    "sweep_level_index": int(level_index),
                    "target_raw_weight": float(target_value),
                    "target_normalized_weight": float(normalized[target]),
                }
            )
            preferences.append(preference)
    return preferences


def generate_random_preferences():
    # 随机采样用于查看权重区间内部是否存在非网格点的好组合。
    # (Random sampling can reveal good combinations away from the grid.)
    preferences = []
    seed = int(os.environ.get("JUC_SWEEP_RANDOM_SEED", "8848"))
    random.seed(seed)
    for idx in range(RANDOM_SAMPLES):
        raw = {
            name: random.uniform(*PREFERENCE_RANGES[name])
            for name in MORL_OBJECTIVE_NAMES
        }
        preferences.append(make_preference(f"random_{idx:03d}", raw))
    return preferences


def generate_preferences():
    if SWEEP_MODE == "ofat":
        preferences = generate_ofat_preferences()
    elif SWEEP_MODE == "representative":
        preferences = generate_representative_preferences()
    elif SWEEP_MODE == "random":
        preferences = generate_random_preferences()
    elif SWEEP_MODE == "grid":
        preferences = generate_grid_preferences()
    else:
        raise ValueError("JUC_SWEEP_MODE must be ofat, grid, representative, or random.")

    if MAX_ROWS > 0:
        preferences = preferences[:MAX_ROWS]
    return preferences


def build_eval_env(sumo_seed):
    # 构建与 tunable 训练完全一致的偏好条件观测环境。
    # (Build the same preference-conditioned observation environment used during training.)
    env = parallel_env(
        net_file=NET_PATH,
        route_file=ROUTE_PATH,
        out_csv_name=None,
        use_gui=USE_GUI,
        num_seconds=SIM_SECONDS,
        reward_fn=custom_bidirectional_green_wave_morl_reward,
        observation_class=MORLBidirectionalETAObservationFunction,
        min_green=MIN_GREEN,
        max_green=MAX_GREEN,
        sumo_seed=sumo_seed,
    )
    env = ss.pettingzoo_env_to_vec_env_v1(env)
    env = ss.concat_vec_envs_v1(
        env,
        num_vec_envs=1,
        num_cpus=1,
        base_class="stable_baselines3",
    )
    env = base.SB3CompatibilityWrapper(env)

    # VecNormalize 是训练时的“输入尺度记忆”，测试时必须加载同一份统计量。
    # (VecNormalize stores the observation scaling learned during training.)
    env = VecNormalize.load(VEC_NORM_PATH, env)
    env.training = False
    env.norm_reward = False
    return env


def finalize_progression(active_segments, progression_rows, final_time):
    # 仿真结束时，仍在主路分段中的车辆也需要结算，否则 no-stop rate 会漏算。
    # (Finalize vehicles that are still inside a progression segment at episode end.)
    for record in active_segments.values():
        record["exit_time"] = final_time
        progression_rows.append(record.copy())
    active_segments.clear()


def summarize_records(vehicle_records, step_wait_sums, step_queue_lengths, signal_state_counts, progression_rows):
    # 1. 全路网等待和排队：每一步求和，再对整轮仿真取平均。
    # (Network metrics: average step-level waiting sum and stopped vehicles.)
    average_waiting_time = float(np.mean(step_wait_sums)) if step_wait_sums else np.nan
    average_queue_length = float(np.mean(step_queue_lengths)) if step_queue_lengths else np.nan
    final_waiting_time = float(step_wait_sums[-1]) if step_wait_sums else np.nan
    final_queue_length = float(step_queue_lengths[-1]) if step_queue_lengths else np.nan

    # 2. 主路和支路单车最大等待：回答“支路是不是被饿死”的问题。
    # (Per-vehicle max waiting helps detect side-street starvation.)
    vehicle_rows = list(vehicle_records.values())
    main_waits = [row["max_waiting"] for row in vehicle_rows if row["route_type"] == "main"]
    side_waits = [row["max_waiting"] for row in vehicle_rows if row["route_type"] == "side"]

    main_mean_max_waiting = float(np.mean(main_waits)) if main_waits else np.nan
    side_mean_max_waiting = float(np.mean(side_waits)) if side_waits else np.nan
    side_max_waiting = float(np.max(side_waits)) if side_waits else np.nan

    # 3. 主路/支路绿灯比例：直接统计真实灯色字符串，不使用 phase 编号。
    # (Green ratios are based on full signal state strings, not phase numbers.)
    main_green_seconds = 0.0
    side_green_seconds = 0.0
    total_signal_seconds = 0.0
    for signal_id in SIGNALS:
        counts = signal_state_counts[signal_id]
        main_green_seconds += counts.get(base.MAIN_GREEN_STATE, 0.0)
        side_green_seconds += counts.get(base.SIDE_GREEN_STATE, 0.0)
        total_signal_seconds += sum(counts.values())

    main_green_ratio = main_green_seconds / total_signal_seconds if total_signal_seconds else np.nan
    side_green_ratio = side_green_seconds / total_signal_seconds if total_signal_seconds else np.nan

    # 4. no-stop rate：主路分段内没有停车的比例，越高说明绿波越像连续直线。
    # (No-stop rate measures whether arterial vehicles pass segments without stopping.)
    if progression_rows:
        no_stop_values = [0.0 if row["had_stop"] else 1.0 for row in progression_rows]
        mean_no_stop_rate = float(np.mean(no_stop_values))
        progression_count = len(progression_rows)
    else:
        mean_no_stop_rate = np.nan
        progression_count = 0

    return {
        "average_waiting_time": average_waiting_time,
        "average_queue_length": average_queue_length,
        "final_waiting_time": final_waiting_time,
        "final_queue_length": final_queue_length,
        "vehicles_seen": len(vehicle_rows),
        "main_vehicles_seen": len(main_waits),
        "side_vehicles_seen": len(side_waits),
        "main_mean_max_waiting": main_mean_max_waiting,
        "side_mean_max_waiting": side_mean_max_waiting,
        "side_max_waiting": side_max_waiting,
        "main_green_ratio": float(main_green_ratio),
        "side_green_ratio": float(side_green_ratio),
        "mean_no_stop_rate": mean_no_stop_rate,
        "progression_segment_count": progression_count,
    }


def run_single_preference(label, normalized_weights, evaluation_seed):
    # 把当前 preference 固定到全局管理器。观测函数和奖励函数都会读取同一组权重。
    # (Fix the current preference for both observation input and reward scalarization.)
    PREFERENCE_MANAGER.current_weights = normalized_weights

    env = build_eval_env(evaluation_seed)
    model = PPO.load(MODEL_PATH, env=env)
    obs = env.reset()

    vehicle_records = {}
    step_wait_sums = []
    step_queue_lengths = []
    signal_state_counts = {signal_id: defaultdict(float) for signal_id in SIGNALS}
    active_segments = {}
    progression_rows = []
    final_time = 0.0

    try:
        while True:
            action, _ = model.predict(obs, deterministic=True)
            obs, _, dones, _ = env.step(action)
            sim_time = safe_traci(final_time, traci.simulation.getTime)
            final_time = sim_time

            # 1. 统计信号灯真实 state，用于主路/支路绿灯比例。
            # (Count full signal states for main/side green ratios.)
            for signal_id in SIGNALS:
                state = safe_traci("", traci.trafficlight.getRedYellowGreenState, signal_id)
                signal_state_counts[signal_id][state] += 1.0

            active_vehicle_ids = list(safe_traci([], traci.vehicle.getIDList))
            current_segment_keys = set()
            step_wait_sum = 0.0
            step_queue_len = 0.0

            for veh_id in active_vehicle_ids:
                group = route_group(veh_id)
                vtype = route_type(group)
                waiting = float(safe_traci(0.0, traci.vehicle.getWaitingTime, veh_id))
                speed = float(safe_traci(0.0, traci.vehicle.getSpeed, veh_id))
                edge_id = safe_traci("", traci.vehicle.getRoadID, veh_id)

                step_wait_sum += waiting
                if speed < 0.1:
                    step_queue_len += 1.0

                record = vehicle_records.setdefault(
                    veh_id,
                    {
                        "vehicle_id": veh_id,
                        "route_group": group,
                        "route_type": vtype,
                        "max_waiting": 0.0,
                        "seen_steps": 0,
                        "stopped_steps": 0,
                    },
                )
                record["max_waiting"] = max(record["max_waiting"], waiting)
                record["seen_steps"] += 1
                if speed < 0.1:
                    record["stopped_steps"] += 1

                # 2. 主路 no-stop 分段追踪：车辆在 A0B0/B0C0/C0B0/B0A0 上是否停车。
                # (Track whether arterial vehicles stop inside progression segments.)
                if edge_id in SEGMENT_BY_EDGE:
                    prog_route, segment_name = SEGMENT_BY_EDGE[edge_id]
                    key = (veh_id, segment_name)
                    current_segment_keys.add(key)
                    segment_record = active_segments.setdefault(
                        key,
                        {
                            "vehicle_id": veh_id,
                            "route_group": prog_route,
                            "segment": segment_name,
                            "entry_time": sim_time,
                            "exit_time": sim_time,
                            "min_speed": speed,
                            "had_stop": False,
                        },
                    )
                    segment_record["exit_time"] = sim_time
                    segment_record["min_speed"] = min(segment_record["min_speed"], speed)
                    if speed < 0.1 or waiting > 0.0:
                        segment_record["had_stop"] = True

            # 3. 离开主路分段的车辆立刻结算，避免下一个路段的数据混在一起。
            # (Finalize segment records once vehicles leave the tracked edge.)
            for key in list(active_segments.keys()):
                if key not in current_segment_keys:
                    progression_rows.append(active_segments.pop(key).copy())

            step_wait_sums.append(step_wait_sum)
            step_queue_lengths.append(step_queue_len)

            if np.any(dones):
                break
    finally:
        finalize_progression(active_segments, progression_rows, final_time)
        env.close()

    metrics = summarize_records(
        vehicle_records=vehicle_records,
        step_wait_sums=step_wait_sums,
        step_queue_lengths=step_queue_lengths,
        signal_state_counts=signal_state_counts,
        progression_rows=progression_rows,
    )
    metrics["preference_id"] = label
    metrics["evaluation_seed"] = int(evaluation_seed)
    return metrics


def main():
    if not ensure_inputs_exist():
        return
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    preferences = generate_preferences()
    print(f"Run: {base.RUN_PREFIX}{RUN_IDX}")
    print(f"Model: {MODEL_PATH}")
    print(f"VecNormalize: {VEC_NORM_PATH}")
    print(f"Sweep mode: {SWEEP_MODE}, preferences: {len(preferences)}")
    active_seeds = EVALUATION_SEEDS if SWEEP_MODE == "ofat" else EVALUATION_SEEDS[:1]
    if not active_seeds:
        raise ValueError("JUC_EVAL_SEEDS must contain at least one integer seed.")
    print(f"Evaluation seeds: {active_seeds}")
    print(f"Output CSV: {RESULT_CSV}")

    result_rows = []
    completed = set()
    if RESUME and os.path.exists(RESULT_CSV):
        previous = pd.read_csv(RESULT_CSV)
        if "evaluation_seed" in previous.columns:
            result_rows = previous.to_dict("records")
            completed = {
                (str(row["preference_id"]), int(row["evaluation_seed"]))
                for row in result_rows
            }
            print(f"Resume enabled: loaded {len(result_rows)} completed evaluations.")

    total = len(preferences) * len(active_seeds)
    sequence = 0
    for label, _raw_weights, normalized_weights, pref_row in preferences:
        for evaluation_seed in active_seeds:
            sequence += 1
            key = (label, int(evaluation_seed))
            if key in completed:
                print(f"[{sequence}/{total}] Skip completed {label}, seed={evaluation_seed}")
                continue

            print(
                f"[{sequence}/{total}] Evaluating {label}, seed={evaluation_seed}: "
                f"{normalized_weights}"
            )
            metrics = run_single_preference(label, normalized_weights, evaluation_seed)
            result_row = pref_row.copy()
            result_row.update(metrics)
            result_rows.append(result_row)
            completed.add(key)

            # Flush after every run so a long multi-seed sweep can resume safely.
            pd.DataFrame(result_rows).to_csv(RESULT_CSV, index=False, encoding="utf-8-sig")
            print(
                "    waiting={:.1f}, queue={:.1f}, no_stop={:.1%}, side_max_wait={:.1f}".format(
                    result_row["average_waiting_time"],
                    result_row["average_queue_length"],
                    result_row["mean_no_stop_rate"],
                    result_row["side_max_waiting"],
                )
            )

    print(f"Finished preference sweep. Saved: {RESULT_CSV}")


if __name__ == "__main__":
    main()
